Twinklebear/ispc-rs

- src/lib.rs
I ran into some issues using ispc-rs for more complex kernels (i.e. Intel's ispc-based texture compressor)
```
cargo:rustc-link-lib=static=kernel
cargo:rustc-link-search=native=H:\Repositories\ibis\Utilities\tex_comp\target\debug\build\tex_comp-87763e9d19faf5b9\out
--- stderr
H:\Repositories\ibis\Utilities\tex_comp\target\debug\build\tex_comp-87763e9d19faf5b9\out\kernel_ispc.h:43:5: error: unknown type name 'bool'
H:\Repositories\ibis\Utilities\tex_comp\target\debug\build\tex_comp-87763e9d19faf5b9\out\kernel_ispc.h:44:5: error: unknown type name 'bool'
H:\Repositories\ibis\Utilities\tex_comp\target\debug\build\tex_comp-87763e9d19faf5b9\out\kernel_ispc.h:54:5: error: unknown type name 'bool'
H:\Repositories\ibis\Utilities\tex_comp\target\debug\build\tex_comp-87763e9d19faf5b9\out\kernel_ispc …
```
> Fix compilation error of 'bool' types with bindgen

- Cargo.toml
- compile/Cargo.toml
- compile/src/lib.rs
- runtime/Cargo.toml
Updated dependencies - especially bindgen, which itself depends on clang-sys and can cause versioning problems when other crates in a project also depend on pre-built clang.
> Updated dependencies

- runtime/src/lib.rs
* Fix change detection for by setting the full path of rs and lib file, otherwise the build script gets evaluated at each run, the problem arises when the crate using the runtime is down the dependency graph causing all it's children to be compiled.
* Using target instead of host, to build for cross compilation scenarios (not tested)
> Fix Cargo change detection in the runtime

- compile/src/opt.rs
This would be useful for reusing isa configs.
> add Clone, Copy and PartialEq for enum TargetISA

- runtime/Cargo.toml
- runtime/src/lib.rs
- runtime/src/task.rs
The aligned_alloc crate was declared deprecated by its creator 17 months ago in favor of std::alloc. While it was working correctly, it could cause issues with crate versions banned by cargo deny, since the dependencies used by it were old.
These changed replace the usage of aligned_alloc with std::alloc from the standard library. The new code was tested within a private repo, with no noticeable differences in the output.
> Replace usage of aligned_alloc with std::alloc

- examples/custom_tasksys/Cargo.toml
- examples/custom_tasksys/src/main.rs
This crate has been deprecated and yanked in favour of the stabilised `std::alloc` APIs.  Without this change it cannot be built.
> examples/custom_tasksys: Replace yanked `aligned_alloc` with `std::alloc`

- compile/src/lib.rs
By default `bindgen` emits bindings for every item in the provided header, which are typically platform- and architecture-specific defines from `stdint.h` and `stdbool.h`.  This is noisy and unnecessary as the function signatures typically don't use any of these.
By allowing the user to set a custom list of function names, bindgen only emits bindings for said functions and any type(s) they (recursively) reference.
Unfortunately `bindgen::Builder` cannot be cloned and is moved by every call, which doesn't allow us to call `.generate()` on it multiple times (and neatly add the `header()` without updating the underlying struct).  In contrast, `Config::compile()` here borrows `self` and requires the builder struct to be reusable across possibly multiple calls on the same `Config`.  For this …
> compile: Add minimal `bindgen` `allowlist_function()` support

- examples/aobench/Cargo.toml
- examples/aobench/src/main.rs
- examples/ddvol/Cargo.toml
- examples/ddvol/scenes/tacc-turbulence.json
- examples/ddvol/src/main.rs
- examples/ddvol/src/raw.rs
- examples/mandelbrot/Cargo.toml
- examples/mandelbrot/src/main.rs
- examples/perlin/Cargo.toml
- examples/perlin/src/main.rs
- examples/rt/Cargo.toml
- examples/rt/src/main.rs
I recently enabled dependabot security alerts (not to be confused with regular dependabot update PRs) and it triggered on my fork of `ispc-rs`: while only the examples that aren't released, it's good to give them some TLC.
> examples: Update dependencies, specifically `image` to get rid of CVE-2020-35916

- Cargo.toml
- compile/Cargo.toml
- runtime/Cargo.toml
Commit ad85f13 ("Seems like edition in workspace isn't applied? Update all to 2021") found that `workspace.edition` isn't a valid key and added it to most crates' individual `[package]` table, but didn't remove the key from `[workspace]` nor added it to the `compile` and `runtime` crates:
```
warning: ispc-rs/Cargo.toml: unused manifest key: workspace.edition
```
Note that `[workspace.package] edition = "2021"` exists since Rust 1.64, but still requires `[package] edition.workspace = true` to be repeated in every individual `Cargo.toml` for it to be inherited: https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table
> Add missing `edition = "2021"` to `compile` and `runtime` crates

- Cargo.toml
- compile/Cargo.toml
- compile/src/lib.rs
- examples/simple/build.rs
- runtime/Cargo.toml
Depends on #21 for `pub use bindgen;` (perhaps all `extern crate` should be replaced since moving to edition 2021?)
As announced earlier in #20 when introducing `BindgenOptions`, upstream `bindgen` didn't yet allow cloning nor copying their `Builder` struct, limiting it to generate a single binding per `Builder` object.  This doesn't fit with ispc-rs's `Config` struct which explicitly allows multiple libraries to be compiled using (partially) the same base configuration (barring any side-effects from `fn compile(&mut self, lib)` updating various fields depending on `lib`).
This issue has since been addressed upstream, and now allows us to move and clone the `bindgen::Builder` around instead of implementing a very limited subset of config fields and manually reconstructing the builder …
> compile: Upgrade to `bindgen 0.61` and use `Builder` with `Clone`

- .github/workflows/main.yml
- Cargo.toml
- compile/Cargo.toml
- compile/src/lib.rs
- compile/src/opt.rs
- examples/ddvol/src/fb.rs
- examples/ddvol/src/main.rs
- examples/ddvol/src/scene.rs
- examples/ddvol/src/vec3.rs
- examples/ddvol/src/vol.rs
- examples/rt/src/camera.rs
- examples/rt/src/geom.rs
- examples/rt/src/lights.rs
- examples/rt/src/main.rs
- examples/rt/src/material.rs
- examples/rt/src/scene.rs
- examples/rt/src/vec3f.rs
- examples/simple/build.rs
- runtime/Cargo.toml
- runtime/src/task.rs
Depends on #21, and #22 as the latest `bindgen` fixes clippy lints in generated code
As discussed previously it'd be nice to keep `ispc-rs` "free" of simple "code smells" commonly pointed out by `clippy`.  This is easy to guard by disallowing any clippy warnings from trickling into the codebase through PRs via an extra CI check.
Downside is that Rust upgrades every 6 weeks and usually enables new or improves existing lints, resulting in unrelated CI errors caused by existing code being punted on unsuspecting contributors in newly opened PRs.  But these are typically easy to resolve in a separate PR, or to be caught early when (also) running the CI job on a schedule.
> Run clippy in the CI with warnings disallowed

- .github/workflows/main.yml
GitHub's `runner-images` already come preloaded with all the Rust components needed, and `actions-rs` hasn't been maintained for the longest time and is now spitting useless NodeJS deprecation warnings.
Fortunately this CI script is already using plain `run: cargo ...`, other repos were using the slower, more verbose and less relatable `actions-rs/cargo` step for this.
---
Sidenote: this may not update to the latest `stable` as soon as it releases, but that'd be easy to fix with a `run: rustup update` if desired - even if slower than giving GitHub a few days to propagate updated containers through their ecosystem.
> CI: Drop unnecessary `actions-rs` toolchain setup

- .github/workflows/main.yml
Make sure we're compatible with the latest compiler release that just dropped: https://github.com/ispc/ispc/releases/tag/v1.20.0
> ci: Test binaries on latest ISPC 1.20 release

- README.md
The CI badge was still pointing to the extinct Travis CI, and there were no badges for docs.rs nor the license.
Also address some inconsistent heading styles: only the top crate header should be H1, the rest should recursively be H2, H3 etc.
> README: Fix CI badge and add docs.rs/license badge

- compile/Cargo.toml
- compile/src/lib.rs
The `gcc` crate hasn't been updated for 5 years and clearly states that is deprecated after a rename to `cc`.
More importantly we're cross-compiling some Windows ISPC code to aarch64 and while GitHub's actions runners definitely have [all the cross-compiling packages installed] the old `gcc` crate was complaining that it could not find `lib.exe` for the desired target.
Note that this strangely happened to work fine on a developer machine, but it is unclear why.
[all the cross-compiling packages installed]: https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#workloads-components-and-extensions
> compile: Replace ancient `gcc` crate with `cc`

- .github/workflows/main.yml
`brew` keeps horribly breaking, and a `brew install ispc` after a `brew upgrade` takes an insulting 13 minutes to also update all kinds of unrelated "formulae" that are irrelevant to the request to simply upgrade `ispc` (and direct dependencies).  And it doesn't even allow us to pin the version to match the Linux and Windows jobs.
This is simply solved by mimicking the Linux/Windows install process, by downloading the latest versioned `ispc` binary from GitHub, extracting it, and passing the path to `GITHUB_PATH`.
Also clean up some inconsistencies in env var resolving, to all resolve them inside the shell script (via `$var` on UNIX and `$env:var` on Windows) as `${{ env.var }}` doesn't work in every context (i.e. to get to `GITHUB_PATH`).
> MacOS: Install `ispc` by downloading **versioned** release from GitHub

- runtime/src/lib.rs
Having a `#[allow]` on top of `include!()` only applies to the first statement in the included file, hence has very little effect. Furthermore `bindgen 0.70.1` now emits the necessary `#[allow]`s already to appease `clippy`, making this redundant even if it was correctly applying to the surrounding module with `#![allow]`.
> Remove broken `#[allow]` on `include!()` from #34

- compile/src/lib.rs
This adds support for enabling `llvm intrinsics` Info in the docs here https://ispc.github.io/ispc.html#llvm-intrinsic-functions
> Added LLVM intrinsics compile option

- compile/src/opt.rs
ISPC 1.26 added generic ISA selection flags.  These unfortunately require setting a CPU explicitly, and cannot be mixed & matched (only one generic ISA must be set at any time).
> compile: Add new `generic-*` ISA flags

- compile/src/lib.rs
- compile/src/opt.rs
This makes the CI in both PRs/pushes and the nightly runs happy again.
While at it, I've replaced some `to_string()` calls with a format string which should be ever so slightly more efficient by saving on an allocation.
> Fix all new clippy lints since Rust 1.88
